name: Staffin
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: The Staffin Family
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7da5e2'
    - '#221b1f'
    - '#e9b695'
    - '#6d5d4e'
    - '#dd3a23'
  brandStrength: 0.5625
  lightness: 0.4629479767754674
  saturation: 0.40828350465744734
  rhythmicContrast: 0.6189009530935436
purpose: []
